### ISSUE TITLE
Multiple Queue

### ISSUE THREAD

**Issue by fatto** [GameTechDev/IntroductionToVulkan#1]
In VulkanCommon::CreateDevice [#L318](https://github.com/GameTechDev/IntroductionToVulkan/blob/master/Project/Common/VulkanCommon.cpp#L318) queueCreateInfoCount should be changed to `queue_create_infos.size()` from 1 to cover the case when multiple queue are needed

**Comment by Ekzuzy** [comment]
You are right. Somehow I missed that. Thank You very much!
