### ISSUE TITLE
VK_API_VERSION macro is not defined in latest Vulkan SDK

### ISSUE THREAD

**Issue by GabrielMajeri** [GameTechDev/IntroductionToVulkan#11]
In the latest LunarG SDK (1.0.17.0), the macro VK_API_VERSION is not defined any more.

From the latest vulkan.h file from the SDK:

``` c++
// DEPRECATED: This define has been removed. Specific version defines (e.g. VK_API_VERSION_1_0), or the VK_MAKE_VERSION macro, should be used instead.
//#define VK_API_VERSION VK_MAKE_VERSION(1, 0, 0)
```

  I've found this issue when compiling the Tutorial01.cpp file, specifically ~ line 110:

``` c++
VkApplicationInfo application_info = {
      ...
      VK_API_VERSION   // uint32_t  apiVersion
    };
```

The solution I found is to use VK_API_VERSION_1_0, as the comment said.

Perhaps a solution that would would work with older version is something like

``` c++
#if VK_HEADER_VERSION >= 17
  #define VK_API_VERSION VK_API_VERSION_1_0
#else
 // Just use the macro already defined in vulkan.h
#endif
```

**Comment by Ekzuzy** [comment]
Thanks for the info! I will look at it.

**Comment by Ekzuzy** [comment]
Maybe a solution would be to check if this definition exists:

#include "vulkan.h"
#ifndef VK_API_VERSION
#define VK_API_VERSION VK_MAKE_VERSION(1, 0, 0)
#endif

But I think I will stick with just VK_MAKE_VERSION(1, 0, 0) to not clutter the code. Patch version doesn't matter from the compatibility perspective so it should be enough.

**Comment by GabrielMajeri** [comment]
OK, thanks for the fix.
