### ISSUE TITLE
vkGetInstanceProcAddr is already defined.

### ISSUE THREAD

**Issue by mmostajab** [GameTechDev/IntroductionToVulkan#12]
I am using the API coming from 

https://github.com/KhronosGroup/Vulkan-Docs

but it seems the vkGetInstanceProcAddr definition is already included into the vulkan.h.

**Comment by Ekzuzy** [comment]
Are You sure You have "VK_NO_PROTOTYPES" defined before vulkan.h file is included? Vulkan.h file can contain definitions for Vulkan functions. This is useful if we want to statically link with a Vulkan Runtime library.
What IDE are You using?

**Comment by mmostajab** [comment]
With defining VK_NO_PROTOTYPES, the problem solved.

I am using VS2015 (vs14.0)

**Comment by Ekzuzy** [comment]
Good to know. I'm surprised though, because this definition is included in a "CMakeLists.txt" file from which Visual Studio solution is generated. Nevertheless, I'm glad I could help! :-)
