### ISSUE TITLE
(very minor) namespace comment in Tutorial01.cpp

### ISSUE THREAD

**Issue by FirefoxMetzger** [GameTechDev/IntroductionToVulkan#13]
Just a very minor thing. The comment signaling the end of the namespace 'ApiWithoutSecrets' reads '// namespace Tutorial'. Aka

```
namespace ApiWithoutSecrets {
// more code here
} // namespace Tutorial
```

really nothing major though.

**Comment by Ekzuzy** [comment]
Thanks for Your keen eye! :-)
