### ISSUE TITLE
Convert CRLF to LF

### ISSUE THREAD

**Issue by joone** [GameTechDev/IntroductionToVulkan#21]
This commit seems to convert LF to CRLF in all source files.  
https://github.com/GameTechDev/IntroductionToVulkan/commit/561ac8c3c7f6b3c71007ed0540b898f900a88cf4
We need to remove this commit and git push --force

**Comment by Ekzuzy** [comment]
Hi. I've converted line endings back to LF (\n). I hope this helps.

**Comment by joone** [comment]
Thanks!
