### ISSUE TITLE
The links for tutorials 5 and 7 are broken

### ISSUE THREAD

**Issue by tuket** [GameTechDev/IntroductionToVulkan#26]
Apparently the links for tutorials 5 and 7 don't work.

These are the links that work for me:
https://www.intel.com/content/www/us/en/developer/articles/training/api-without-secrets-introduction-to-vulkan-part-5.html
https://www.intel.com/content/www/us/en/developer/articles/training/api-without-secrets-introduction-to-vulkan-part-7.html

**Comment by DaveBookout-Intel** [comment]
thanks! i've updated to the links you provided above.
