### ISSUE TITLE
'TRANSFER_DST image usage is not supported by the swap chain!'

### ISSUE THREAD

**Issue by EthanTheGreat** [GameTechDev/IntroductionToVulkan#4]
I used CMake for Visual Studio 2014 64bit.

Once I create the projects, then I compile the tutorial projects.

However, it seems to crash directly after it outputs:
`TRANSFER_DST image usage is not supported by the swap chain!`

I really appreciate the feedback.

**Comment by EthanTheGreat** [comment]
Also, I tried using Vulkan's API-Samples, same weird result...

I can't seem to figure it out.

**Comment by Ekzuzy** [comment]
Hi! Could You tell me what graphics hardware and graphics drivers You are using?

Unfortunately, some hardware vendors may not support some image usages for swap chain - only "color attachment" usage is obligatory. If "transfer dst" usage is not supported, unfortunately some operations on swap chain images need to be performed differently. In example image clears cannot be performed by using vkCmdClearColorImage() function but only through loadOp of a render pass.

Try changing the code so only the "color attachment" usage is set for a swap chain. In Tutorial03 this should work as clears are performed as part of a render pass (You need to change GetSwapChainUsageFlags() in VulkanCommon.cpp). This may also work in Tutorial02 but doesn't have to - vkCmdClearColorImage() which (generally) requires an image to be created with "transfer dst" usage but some hardware vendors may allow this operation to be performed without it.

**Comment by EthanTheGreat** [comment]
Uh yeah sure, it's AMD 390 R9. I'll give it a shot once I get a chance. Thanks!

**Comment by Ekzuzy** [comment]
Unfortunately, right now I don't have access to any AMD graphics card that supports Vulkan. But I have removed "transfer_dst" usage from VulkanCommon class so You shouldn't have any problems with code samples 03 and 04.
I can't change sample code 02 because it would make Tutorial02 drastically longer (and it is long enough already).

**Comment by Overv** [comment]
This is a bug in the AMD driver. It does support transfer operations, but it currently fails to return the capability bit.

**Comment by Ekzuzy** [comment]
Good to know, thanks for the information!
Nevertheless, I think transfer operations are not too common. Image clear should be done through a loadOp of a render pass. Copying image data from one image to another is a bit wasteful when there is a possibility to render data directly into an image. So, in case of a swap chain, transfer_dst usage shoulnd't be necessary in most common rendering scenarios.

**Comment by Ekzuzy** [comment]
@EthanTheGreat 
Hi! Did You check my latest code updates? Do they work correctly on Your hardware? You shouldn't have problems with swapchain image usages now.

**Comment by EthanTheGreat** [comment]
Yes.... Wow Ekzuzy!!!

Thanks a bunch dude!

**Comment by Ekzuzy** [comment]
Great news! Thanks for the info :-).
