### ISSUE TITLE
Windows shaders loading from wrong relative path

### ISSUE THREAD

**Issue by gigadude** [GameTechDev/IntroductionToVulkan#5]
If you use `build.bat` to create the project for you it runs from the generated `build` directory (where the .vcxproj files are), and the shader paths need to be modified to `"../TutorialXX/DataXX/..."`. It might be better to copy the shaders there with a [post-build step](http://stackoverflow.com/questions/9994045/copy-target-file-to-another-location-in-a-post-build-step-in-cmake).

**Comment by Ekzuzy** [comment]
I've updated CMakeLists.txt file to copy the DataXX folders to build folder.
Unfortunately, on Windows executables are built into debug or release folders so additional copy operation is needed for the compiled application to see DataXX folder. But when debugging in Visual Studio, DataXX folders should be visible by default now.
