### ISSUE TITLE
Stage to wait for semaphore in tutorial 3

### ISSUE THREAD

**Issue by Overv** [GameTechDev/IntroductionToVulkan#6]
Tutorial 3 uses mostly the same drawing code as tutorial 2, but since we're doing a drawing operation instead of a transfer operation now, shouldn't `VK_PIPELINE_STAGE_TRANSFER_BIT` be changed to something like `VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT` with regards to waiting on the image available semaphore?

**Comment by Ekzuzy** [comment]
Yes, You are right. Code was copied & pasted from tutorial02 and I must have missed that. I was wondering about it recently when I was updating code sample 04. I think color_attachment_output stage should be enough as earlier pipeline stages don't access swap chain images in this example. But I must check when image clears (as part of a loadOp in a render pass) are done.

**Comment by Overv** [comment]
Section 29.6 of the specification mentions

> An application can acquire use of a presentable image with vkAcquireNextImageKHR. After acquiring a presentable image and before modifying it, the application must use a synchronization primitive to ensure that the presentation engine has finished reading from the image. The application can then transition the image’s layout, queue rendering commands to it, etc.

It seems that any operation involving the image is forbidden. I think that means that using `VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT` may be the way to go.

On the other hand, the optional pipeline barrier is already waiting for `VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT`, which could mean that `VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT` is safe if it is enabled.

**Comment by Overv** [comment]
I have also noticed that the initial layout of the swap chain images is `VK_IMAGE_LAYOUT_UNDEFINED` (reported by validation layer), so the initial pipeline barrier must always be executed. If the graphics and present queue families are not different, then `VK_QUEUE_FAMILY_IGNORED` should probably be used.

**Comment by Ekzuzy** [comment]
What "initial layout" You have in mind?
1. The one image is created with? or
2. The one in the attachment description of a render pass?

If first - swap chain images are created and managed by a presentation engine and the initial barrier (the one after image is created but before it is first used) is not required. But it is required to transition away from "present_src" layout: "VK_IMAGE_LAYOUT_PRESENT_SRC_KHR: [...] A swapchain’s image [...] must be transitioned away from this layout after calling vkAcquireNextImageKHR."

If second - undefined layout can be used for initial layout during image creation, but it can also be used in barriers as old layout (or initial layout of a render pass). When using this layout, image contents may be discarded during transition, but it may allow driver to perform the transition much faster.

But in general - You are right. Initial transition (after image is created and before it can be used) is always required as images may only be created with undefined or preinitialized layouts.

And thanks for the hint about VK_QUEUE_FAMILY_IGNORED enum, I've somehow overlooked it.

**Comment by Overv** [comment]
Yeah, I had the initial layout the image is created with in mind.

**Comment by Ekzuzy** [comment]
Changed waiting stage of submitInfo from VK_PIPELINE_STAGE_TRANSFER_BIT to VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT (as used in examples in API specification).
