### ISSUE TITLE
Triangle coordinates

### ISSUE THREAD

**Issue by Overv** [GameTechDev/IntroductionToVulkan#7]
Chapter 3 uses the following coordinates for the triangle:

`vec2 pos[3] = vec2[3]( vec2(-0.7, 0.7), vec2(0.7, 0.7), vec2(0.0, -0.7) );`

However, when considering [normalized device coordinates](https://lva.cg.tuwien.ac.at/ecg/wiki/lib/exe/fetch.php?media=students:normalized_device_coordinates.png), shouldn't the triangle be pointing downwards?

**Comment by Ekzuzy** [comment]
Vulkan's coordinate system is different than OpenGL's (more like Direct3D's), Framebuffer's origin (0, 0) is in upper-left corner and, as far as I remember, clip coordinates are similar and go from left to rigth, and from top to bottom, (-1, -1,) in upper-left corner and (1, 1) in lower-right corner.

**Comment by Overv** [comment]
Ah, do you know how to handle this properly with GLM? Functions like `glm::lookAt` result in an upside down view. Right now I use a construct in my vertex shader like

```
vec4 res = ubo.transformationMatrix * vec4(inPos, 1.0);
res.y = -res.y;
gl_Position = res;
```

But that is hardly ideal.

**Comment by Ekzuzy** [comment]
This solution, though not too pretty, is quite popular. I'm not sure, but I think I've seen it in Unity3D which uses similar code to fix the differences between OGL and D3D. ;-)
Whether it can be fixed on a GLM level... right now I can't tell You. I haven't used GLM for a very long time. I will check at work and consult with my colleagues but there may not be other workaround than the one You presented. And even if there is, it may not be faster.

**Comment by Ekzuzy** [comment]
Hi! I've checked the GLM library and there is a solution You could use, though it may not be too easy. Just by using proper functions (apart from scaling in Y direction by -1) You may not achieve the desired effect. But You can modify the source code responsible for preparing matrices (especially perspective/frustum matrix). This way You can "adjust" the GLM to the coordinate systems used in Vulkan.
