### ISSUE TITLE
Validation Layer Failure

### ISSUE THREAD

**Issue by llcdraco** [GameTechDev/IntroductionToVulkan#8]
Hello. If you enable VK_LAYER_LUNARG_standard_validation in sample 2(I did not test other samples) you will get invalid surface pointer after vkCreateWin32SurfaceKHR call. It may be bug in your code or bug in driver. I do not see the error. However, if you run e.g. Stardust demo it works fine.

**Comment by Ekzuzy** [comment]
I've tested the examples with LunarG validation layers. But maybe I've done that with not all of them or maybe some of my recent changes broke something. I will check it and get back to You soon. Thanks for the info!

**Comment by Ekzuzy** [comment]
I cannot reproduce this problem. I've tried enabling validation layers through environment variables and through code, but each time sample 02 executes without any problem. Well, validation layers report some warnings (not connected with the issue You've reported) but I don't agree with them (yet).
I've tested it with the latest available SDK version (1.0.11.1).

**Comment by llcdraco** [comment]
I am running your demo on Windows7, SDK 1.0.11.1, NVidia driver is 364.91 with Vulkan version 1.0.8.
As long as I enable validation layers I get the following error:
Exception thrown at 0x0000000069DC5E48 (nvoglv64.dll) in 02-Swapchain.exe: 0xC0000005: Access violation reading location 0x0000000000000001 in vkCreateSwapchainKHR.

vkCreateWin32SurfaceKHR returns 0x0000000000000001 for VkSurfaceKHR and vkCreateSwapchainKHR crashes. However, if I disable validation layers it works fine. Notice nvoglv64.dll - I have no idea why it had appeared here.

**Comment by Ekzuzy** [comment]
First, as far as I know, Nvidia "merged" Vulkan and OpenGL in their driver and both APIs can "cooperate". So it's nothing strange that some Vulkan errors appear in OpenGL libraries.

Do You enable validation layers directly in code or through environment variables?

**Comment by llcdraco** [comment]
I enable validation layers directly in code.

**Comment by llcdraco** [comment]
I was able to handle this. It looks like it is a bug in validation layers (I can not be sure 100% about it of course). I will submit bug to Lunarg. My workaround was the following: instead of using "VK_LAYER_LUNARG_standard_validation" I requested  full list of layers.
After that it worked.
